/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef echo_TYPES_H
#define echo_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace ff {

typedef struct _echo_thrift_in_t__isset {
  _echo_thrift_in_t__isset() : data(false) {}
  bool data;
} _echo_thrift_in_t__isset;

class echo_thrift_in_t {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  echo_thrift_in_t() : data() {
  }

  virtual ~echo_thrift_in_t() throw() {}

  std::string data;

  _echo_thrift_in_t__isset __isset;

  void __set_data(const std::string& val) {
    data = val;
  }

  bool operator == (const echo_thrift_in_t & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const echo_thrift_in_t &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const echo_thrift_in_t & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(echo_thrift_in_t &a, echo_thrift_in_t &b);

typedef struct _echo_thrift_out_t__isset {
  _echo_thrift_out_t__isset() : data(false) {}
  bool data;
} _echo_thrift_out_t__isset;

class echo_thrift_out_t {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  echo_thrift_out_t() : data() {
  }

  virtual ~echo_thrift_out_t() throw() {}

  std::string data;

  _echo_thrift_out_t__isset __isset;

  void __set_data(const std::string& val) {
    data = val;
  }

  bool operator == (const echo_thrift_out_t & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const echo_thrift_out_t &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const echo_thrift_out_t & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(echo_thrift_out_t &a, echo_thrift_out_t &b);

} // namespace

#endif
